from typing import Protocol, Optional
from ..domain.models import DraftResult


class DraftGeneratorPort(Protocol):
    def generate_hooks(self, company_intel: dict, sender_profile: dict, count: int = 3) -> list[dict]: ...
    def draft(self, hook: dict, company_intel: dict, sender_profile: dict, recipient_name: str) -> DraftResult: ...
    def revise(self, draft: DraftResult, violations: list[str]) -> DraftResult: ...


class ValidatorPort(Protocol):
    def check_self_review(self, draft: DraftResult) -> list[str]: ...


class QAGatewayPort(Protocol):
    def validate_email(self, payload: dict) -> dict: ...


class CampaignRepositoryPort(Protocol):
    def is_do_not_contact(self, email: str) -> bool: ...
    def in_ats_pipeline(self, email: str, job_id: str) -> bool: ...
    def sent_today_count(self) -> int: ...
    def sent_to_company_30d(self, company: str) -> int: ...
    def get_match_score(self, job_id: str) -> Optional[int]: ...
    def already_sent(self, email: str, job_id: str) -> bool: ...
    def create_draft_campaign(self, draft: DraftResult, request) -> str: ...
    def get_campaign(self, campaign_id: str): ...
    def get_user_config(self): ...
    def mark_campaign_sent(self, campaign_id: str, message_id: str) -> None: ...
    def cancel_pending_followups(self, campaign_id: str) -> None: ...
    def add_to_do_not_contact(self, email: str) -> None: ...


class EventRepositoryPort(Protocol):
    def record_sent(self, campaign_id: str, message_id: str) -> None: ...
    def record_reply(self, campaign_id: str, reply_type: str, reply_text: str) -> None: ...


class TrackerPort(Protocol):
    def inject_pixel(self, body_html: str, campaign_id: str) -> str: ...


class MailerTransportPort(Protocol):
    def send(self, to_email: str, to_name: str, subject: str, body_html: str, body_text: str) -> str: ...


class TimezonePort(Protocol):
    def infer_recipient_timezone(self, recipient_email: str, company_intel: dict): ...
