from .registry import (
    DRAFTER_SYSTEM_PROMPT,
    HOOK_SYSTEM_PROMPT,
    REVISION_SYSTEM_PROMPT,
    FOLLOWUP_SYSTEM_PROMPT,
)

__all__ = [
    "DRAFTER_SYSTEM_PROMPT",
    "HOOK_SYSTEM_PROMPT",
    "REVISION_SYSTEM_PROMPT",
    "FOLLOWUP_SYSTEM_PROMPT",
]
