#!/usr/bin/env python3
"""Start the dev stack with automatic OS/arch detection."""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

from host_platform import compose_override_yaml, detect_host_platform, print_detection  # noqa: E402


def _generate_fernet_key() -> str:
    import base64
    import os

    return base64.urlsafe_b64encode(os.urandom(32)).decode()


def ensure_env_file(env_path: Path) -> None:
    if env_path.exists():
        return

    key = _generate_fernet_key()
    env_path.write_text(
        "\n".join(
            [
                "# Auto-generated by scripts/dev_up.py",
                "ANTHROPIC_API_KEY=",
                f"GTM_SMTP_ENCRYPTION_KEY={key}",
                "DATABASE_URL=postgresql://gtm:gtm@localhost:5432/gtm",
                "SMTP_HOST=mailpit",
                "SMTP_PORT=1025",
                "SMTP_USER=coldcraft",
                "FROM_EMAIL=coldcraft@localhost",
                "FROM_NAME=Coldcraft Dev",
                "",
            ]
        ),
        encoding="utf-8",
    )
    print(f"Created {env_path.name} with a generated Fernet key.")


def write_compose_override(path: Path, host) -> None:
    path.write_text(compose_override_yaml(host), encoding="utf-8")


def run_compose(extra_args: list[str]) -> int:
    override = ROOT / "docker-compose.platform.yml"
    cmd = [
        "docker",
        "compose",
        "-f",
        str(ROOT / "docker-compose.yml"),
        "-f",
        str(override),
        *extra_args,
    ]
    return subprocess.call(cmd, cwd=ROOT)


def main() -> int:
    parser = argparse.ArgumentParser(description="Start Coldcraft dev stack")
    parser.add_argument("args", nargs="*", help="Extra docker compose args (default: up --build -d)")
    ns = parser.parse_args()
    extra = ns.args or ["up", "--build", "-d", "--remove-orphans"]

    host = detect_host_platform()
    print_detection(host)

    ensure_env_file(ROOT / ".env")
    write_compose_override(ROOT / "docker-compose.platform.yml", host)

    print("Starting services…", flush=True)
    print("  API + OpenAPI:  http://localhost:8000/docs", flush=True)
    print("  Mailpit (mail): http://localhost:8025", flush=True)
    print("  UI (Vite dev):  http://localhost:5173", flush=True)
    return run_compose(extra)


if __name__ == "__main__":
    raise SystemExit(main())