"""Detect host OS/architecture and map to Docker platform settings."""

from __future__ import annotations

import platform
import sys
from dataclasses import dataclass


@dataclass(frozen=True)
class HostPlatform:
    os_name: str
    arch: str
    docker_platform: str
    is_apple_silicon: bool
    uses_emulation: bool

    @property
    def label(self) -> str:
        if self.is_apple_silicon:
            return "macOS (Apple Silicon)"
        if self.os_name == "macos" and self.arch in {"x86_64", "amd64"}:
            return "macOS (Intel)"
        if self.os_name == "windows":
            return f"Windows ({self.arch})"
        if self.os_name == "linux":
            return f"Linux ({self.arch})"
        return f"{self.os_name} ({self.arch})"


def _normalize_arch(machine: str) -> str:
    arch = machine.lower()
    if arch in {"arm64", "aarch64"}:
        return "arm64"
    if arch in {"x86_64", "amd64", "x64", "i386", "i686"}:
        return "amd64"
    return arch


def detect_host_platform() -> HostPlatform:
    system = platform.system().lower()
    arch = _normalize_arch(platform.machine())

    os_name = {
        "darwin": "macos",
        "linux": "linux",
        "windows": "windows",
    }.get(system, system)

    docker_platform = "linux/arm64" if arch == "arm64" else "linux/amd64"
    is_apple_silicon = os_name == "macos" and arch == "arm64"
    uses_emulation = False

    return HostPlatform(
        os_name=os_name,
        arch=arch,
        docker_platform=docker_platform,
        is_apple_silicon=is_apple_silicon,
        uses_emulation=uses_emulation,
    )


def compose_override_yaml(host: HostPlatform) -> str:
    mail_image = "axllent/mailpit:latest"
    return f"""# Auto-generated by scripts/dev_up.py — do not edit manually.
# Host: {host.label} → {host.docker_platform}

services:
  mailpit:
    image: {mail_image}
    platform: {host.docker_platform}

  api:
    platform: {host.docker_platform}
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - {host.docker_platform}
"""


def print_detection(host: HostPlatform) -> None:
    print(f"Detected: {host.label} → Docker platform {host.docker_platform}", flush=True)
    if host.is_apple_silicon:
        print("Using native ARM images (Mailpit, Postgres) — no x86 emulation.", flush=True)
    elif host.arch == "arm64":
        print("Using native ARM64 images.", flush=True)
    else:
        print("Using native AMD64 images.", flush=True)


if __name__ == "__main__":
    print_detection(detect_host_platform())
    sys.exit(0)